// This file overrides the built-in Node.js runner
// For more information see http://docs.c9.io:8080/#!/api/run-method-run
{
  "cmd": [
    "/usr/local/lib/node_modules/forever/bin/forever",
    "start",
    "${debug?--nocrankshaft}",
    "${debug?--nolazy}",
    "${debug?`node --version | grep -vqE \"v0\\..\\.\" && echo --nodead_code_elimination`}",
    "${debug?--debug-brk=15454}",
    "$file",
    "$args"
  ],
  "debugger": "v8",
  "debugport": 15454,
  "selector": "source.js"
}
