// This file overrides the built-in Node.js runner
// For more information see http://docs.c9.io:8080/#!/api/run-method-run
{
  "cmd": [
    "node",
    "${debug?--nocrankshaft}",
    "${debug?--nolazy}",
    "${debug?`node --version | grep -vqE \"v0\\..\\.\" && echo --nodead_code_elimination`}",
    "${debug?--debug-brk=15452}",
    "$file",
    "$args"
  ],
  "debugger": "v8",
  "debugport": 15452,
  "selector": "source.js"
}
